name: community_material_icon
description: A community material design icon
version: 0.1.3
author: rio permana <rio.prmn@gmail.com>
homepage: https://github.com/ripsware/community_material_icon

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: MaterialDesignIconFont
      fonts:
        - asset: packages/community_material_icon/fonts/materialdesignicons-webfont.ttf